apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
     app: nginx
     environment: prod
spec:
  containers:
    name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80        
